# Generated by Django 6.1 on 2026-08-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('check_type', models.CharField(choices=[('threshold', 'Threshold'), ('status_expect', 'Status Expect'), ('script', 'Script'), ('composite', 'Composite')], default='threshold', max_length=16)),
                ('metric', models.CharField(blank=True, max_length=128)),
                ('operator', models.CharField(default='>', max_length=8)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('expected_value', models.CharField(blank=True, max_length=128)),
                ('weight', models.IntegerField(default=1)),
                ('severity', models.CharField(default='warning', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='InspectRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(default='cron', max_length=8)),
                ('status', models.CharField(default='running', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_devices', models.IntegerField(default=0)),
                ('abnormal_devices', models.IntegerField(default=0)),
                ('health_score_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_url', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('cron', models.CharField(blank=True, max_length=32)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField()),
                ('status', models.CharField(default='pass', max_length=8)),
                ('actual_value', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspect.inspectitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspect.inspectrun')),
            ],
        ),
        migrations.AddField(
            model_name='inspectrun',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='inspect.inspecttask'),
        ),
        migrations.AddField(
            model_name='inspecttask',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inspect.inspecttemplate'),
        ),
        migrations.AddField(
            model_name='inspectrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspect.inspecttemplate'),
        ),
        migrations.AddField(
            model_name='inspectitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspect.inspecttemplate'),
        ),
        migrations.CreateModel(
            name='InspectRunDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('health_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('pass_count', models.IntegerField(default=0)),
                ('warn_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_results', to='inspect.inspectrun')),
            ],
            options={
                'unique_together': {('run', 'device_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inspectitem',
            unique_together={('template', 'code')},
        ),
    ]
