# Generated by Django 6.1 on 2026-09-02 19:24

import common.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('app_id', models.CharField(max_length=128)),
                ('app_secret', common.crypto.EncryptedTextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('mock_mode', models.BooleanField(default=False)),
                ('auto_provision', models.BooleanField(default=True)),
                ('default_role_id', models.BigIntegerField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': '飞书应用(SSO)',
                'ordering': ['id'],
            },
        ),
    ]
