name: nops-app

networks:
  nops-net:
    external: true
    name: nops-net

services:
  api:
    build: .
    container_name: nops-api
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000 -w 4 --timeout 120
    env_file: .env
    environment:
      DJANGO_DEBUG: "0"
      POSTGRES_HOST: postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      VM_URL: http://victoriametrics:8428
      MINIO_ENDPOINT: minio:9000
    ports:
      - "8000:8000"
    networks: [nops-net]

  worker:
    build: .
    container_name: nops-worker
    command: celery -A config worker -l info -Q nops -c 8
    env_file: .env
    environment:
      DJANGO_DEBUG: "0"
      POSTGRES_HOST: postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      VM_URL: http://victoriametrics:8428
      MINIO_ENDPOINT: minio:9000
    networks: [nops-net]

  beat:
    build: .
    container_name: nops-beat
    command: celery -A config beat -l info
    env_file: .env
    environment:
      DJANGO_DEBUG: "0"
      POSTGRES_HOST: postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      VM_URL: http://victoriametrics:8428
      MINIO_ENDPOINT: minio:9000
    networks: [nops-net]

  syslog:
    build: .
    container_name: nops-syslog
    command: python services/syslog_server.py
    env_file: .env
    environment:
      DJANGO_DEBUG: "0"
      POSTGRES_HOST: postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      VM_URL: http://victoriametrics:8428
    ports:
      - "514:514/udp"
    networks: [nops-net]

  web:
    build:
      context: ../frontend
    container_name: nops-web
    ports:
      - "8090:80"
    depends_on:
      - api
    networks: [nops-net]
