# Generated by Django 6.1 on 2026-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('region_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='active', max_length=16)),
                ('capacity', models.IntegerField(default=300)),
                ('current_load', models.IntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(default='syslog', max_length=16)),
                ('severity', models.SmallIntegerField(db_index=True, default=6)),
                ('facility', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.BigIntegerField(db_index=True)),
                ('command', models.TextField()),
                ('output_url', models.CharField(blank=True, max_length=512)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('channel', models.CharField(default='web_cli', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('command_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrometheusTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('instance_label', models.CharField(max_length=128)),
                ('job_label', models.CharField(default='node', max_length=64)),
                ('last_scrape_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_ok', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('device_id', 'instance_label')},
            },
        ),
    ]
