# Generated by Django 6.1 on 2026-09-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('report_type', models.CharField(choices=[('inventory', '设备台账快照'), ('alerts', '告警态势快照'), ('changes', '变更/事件快照'), ('ncm', '配置/基线快照')], db_index=True, max_length=16)),
                ('hour', models.IntegerField(default=7, help_text='期望生成小时（0-23，展示用；v1 每日批任务统一触发）')),
                ('enabled', models.BooleanField(default=True)),
                ('notify_channel_ids', models.JSONField(blank=True, default=list)),
                ('receivers', models.JSONField(blank=True, default=list, help_text='站内接收人 user_id 列表（占位）')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '报表订阅',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('inventory', '设备台账快照'), ('alerts', '告警态势快照'), ('changes', '变更/事件快照'), ('ncm', '配置/基线快照')], db_index=True, max_length=16)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('content', models.JSONField(blank=True, default=dict)),
                ('built_by', models.CharField(default='manual', max_length=8)),
                ('duration_ms', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': '报表快照',
                'ordering': ['-period_start'],
                'unique_together': {('report_type', 'period_start')},
            },
        ),
    ]
