# Generated by Django 6.1 on 2026-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('acl', 'acl'), ('ipsec', 'ipsec')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['device_id', 'kind'], name='cmdb_techs_dev_kind')],
            },
        ),
    ]
