# Generated by Django 6.1 on 2026-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_techsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsnapshot',
            name='kind',
            field=models.CharField(choices=[('acl', 'acl'), ('nat', 'nat'), ('ipsec', 'ipsec')], max_length=16),
        ),
    ]
