# Generated by Django 6.1 on 2026-09-02 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_alter_techsnapshot_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkQualitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('interface_id', models.BigIntegerField(db_index=True)),
                ('iface_name', models.CharField(blank=True, max_length=64)),
                ('sampled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('in_bps', models.BigIntegerField(default=0)),
                ('out_bps', models.BigIntegerField(default=0)),
                ('in_pps', models.BigIntegerField(default=0)),
                ('out_pps', models.BigIntegerField(default=0)),
                ('in_errors_rate', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('out_errors_rate', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('optical_tx_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optical_rx_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-sampled_at'],
                'indexes': [models.Index(fields=['device_id', 'sampled_at'], name='lqs_dev_samp')],
            },
        ),
    ]
