# Generated by Django 6.1 on 2026-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_linkqualitysample'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinterfacestat',
            name='in_octets_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceinterfacestat',
            name='out_octets_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceinterfacestat',
            name='sampled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
