# Generated by Django 6.1 on 2026-09-02 19:17

import common.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_deviceinterfacestat_in_octets_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmwareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('host', models.CharField(help_text='vCenter 主机/地址', max_length=128)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('secret', common.crypto.EncryptedTextField(blank=True, null=True)),
                ('site_id', models.BigIntegerField(blank=True, null=True)),
                ('region_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mock_vms', models.JSONField(blank=True, default=list, help_text='mock 演练虚机名单（空=内置样例）')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'vCenter 同步源',
                'ordering': ['-id'],
            },
        ),
    ]
