# Generated by Django 6.1 on 2026-08-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('row_no', models.CharField(blank=True, max_length=8)),
                ('col_no', models.CharField(blank=True, max_length=8)),
                ('u_total', models.PositiveSmallIntegerField(default=42)),
                ('rated_power_w', models.IntegerField(blank=True, null=True)),
                ('rated_weight_kg', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['site_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('a_interface_id', models.BigIntegerField(db_index=True)),
                ('b_interface_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('cable_type', models.CharField(choices=[('cat5e', 'Cat5E'), ('cat6', 'Cat6'), ('mm_fiber', 'Mm Fiber'), ('sm_fiber', 'Sm Fiber'), ('jumper', 'Jumper')], default='cat6', max_length=16)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('path_desc', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('lldp', 'Lldp'), ('cdp', 'Cdp')], default='manual', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mismatch', 'Mismatch'), ('planned', 'Planned'), ('removed', 'Removed')], default='active', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'unique_together': {('a_interface_id', 'b_interface_id')},
            },
        ),
        migrations.CreateModel(
            name='RackReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_u', models.PositiveSmallIntegerField()),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dcim.rack')),
            ],
            options={
                'ordering': ['rack_id', 'start_u'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('manager_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dcim.region')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('manager_id', models.BigIntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('bandwidth_mbps', models.IntegerField(blank=True, null=True)),
                ('isp', models.CharField(blank=True, max_length=64)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='dcim.region')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='dcim.site'),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('site', 'name')},
        ),
    ]
