# Generated by Django 6.1 on 2026-08-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='floor_len_m',
            field=models.FloatField(blank=True, help_text='机房长(米)', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='floor_w_m',
            field=models.FloatField(blank=True, help_text='机房宽(米)', null=True),
        ),
        migrations.CreateModel(
            name='SiteObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obj_type', models.CharField(choices=[('rack', 'Rack'), ('ups', 'Ups'), ('ap', 'Ap'), ('power', 'Power'), ('fire', 'Fire'), ('door', 'Door'), ('other', 'Other')], default='other', max_length=16)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('rack_id', models.BigIntegerField(blank=True, null=True)),
                ('x', models.FloatField(default=0, help_text='左上角X(米)')),
                ('y', models.FloatField(default=0, help_text='左上角Y(米)')),
                ('w', models.FloatField(default=0.6, help_text='宽(米)')),
                ('h', models.FloatField(default=1.2, help_text='深/高(米)')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_objects', to='dcim.site')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
