# Generated by Django 6.1 on 2026-09-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0002_site_floor_len_m_site_floor_w_m_siteobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcimTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('rack_in', 'Rack In'), ('rack_out', 'Rack Out'), ('move', 'Move'), ('repair', 'Repair'), ('cable', 'Cable')], max_length=16)),
                ('device_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('u_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('u_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('doing', 'Doing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('assignee', models.CharField(blank=True, max_length=64)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('result', models.CharField(blank=True, max_length=500)),
                ('operator_id', models.BigIntegerField(blank=True, null=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_tickets', to='dcim.rack')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
