# Generated by Django 6.1 on 2026-09-02 19:09
# 注：仅新增 PowerSample；dcimticket 的 kind/status 既有漂移按仓库纪律保持原状（不改）。
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_dcimticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('outlet', models.CharField(blank=True, default='', help_text="输出口（'' 为总路）", max_length=32)),
                ('watts', models.FloatField(blank=True, null=True)),
                ('current_a', models.FloatField(blank=True, null=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('utilization_pct', models.FloatField(blank=True, null=True)),
                ('rated_watts', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('prom', 'Prometheus'), ('snmp', 'SNMP'), ('manual', '手工录入')], default='prom', max_length=8)),
                ('sampled_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': '电源实测样本',
                'ordering': ['-sampled_at'],
            },
        ),
    ]
