# Generated by Django 6.1 on 2026-08-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('topo_type', models.CharField(choices=[('physical_l2', 'Physical L2'), ('l3', 'L3'), ('wireless', 'Wireless'), ('custom', 'Custom')], default='physical_l2', max_length=16)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LldpNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_interface_id', models.BigIntegerField(db_index=True)),
                ('source', models.CharField(default='lldp', max_length=8)),
                ('remote_chassis_id', models.CharField(blank=True, max_length=128)),
                ('remote_hostname', models.CharField(blank=True, max_length=128)),
                ('remote_port_desc', models.CharField(blank=True, max_length=128)),
                ('remote_port_id', models.CharField(blank=True, max_length=128)),
                ('remote_device_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['local_interface_id'],
                'unique_together': {('local_interface_id', 'remote_chassis_id', 'remote_port_id')},
            },
        ),
        migrations.CreateModel(
            name='TopologyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('a_device_id', models.BigIntegerField(db_index=True)),
                ('b_device_id', models.BigIntegerField(db_index=True)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='topo.topology')),
            ],
            options={
                'unique_together': {('topology', 'a_device_id', 'b_device_id')},
            },
        ),
        migrations.CreateModel(
            name='TopologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='topo.topology')),
            ],
            options={
                'unique_together': {('topology', 'device_id')},
            },
        ),
    ]
