# Generated by Django 6.1 on 2026-09-02 15:04

import common.crypto
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biz_type', models.CharField(choices=[('script_run', '脚本执行'), ('change_ticket', '变更单')], default='script_run', max_length=16)),
                ('biz_id', models.BigIntegerField(db_index=True)),
                ('applicant_id', models.BigIntegerField(db_index=True)),
                ('approver_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=8)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('category', models.CharField(blank=True, help_text='分类，如 配置备份/端口操作/巡检处理', max_length=64)),
                ('script_type', models.CharField(choices=[('cli_command', '网络 CLI 命令'), ('python', 'Python 脚本'), ('shell', 'Shell 脚本'), ('ansible', 'Ansible Playbook')], default='cli_command', max_length=16)),
                ('content', common.crypto.EncryptedTextField(help_text='脚本/命令内容（AES-256-GCM 密文存储）')),
                ('params_schema', models.JSONField(blank=True, default=dict, help_text='参数定义 [{key,label,default,required}]，执行时 {{key}} 插值')),
                ('danger_level', models.CharField(choices=[('low', '低危'), ('mid', '中危'), ('high', '高危')], default='low', max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '脚本库',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script_id', models.BigIntegerField(db_index=True)),
                ('script_name_snapshot', models.CharField(blank=True, max_length=128)),
                ('script_type_snapshot', models.CharField(blank=True, max_length=16)),
                ('danger_snapshot', models.CharField(blank=True, max_length=8)),
                ('content_snapshot', common.crypto.EncryptedTextField(blank=True, default='', help_text='执行时刻渲染后的内容快照（加密）')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('trigger', models.CharField(choices=[('manual', '手动'), ('schedule', '周期任务')], default='manual', max_length=8)),
                ('executed_by_id', models.BigIntegerField(db_index=True)),
                ('approval_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('approving', '待审批'), ('running', '执行中'), ('partial_success', '部分成功'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='目标范围 {device_ids:[], gray_first:bool, reason:str}')),
                ('gray_batch', models.JSONField(blank=True, default=dict, help_text='灰度进度 {enabled, total, dispatched}')),
                ('summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptRunDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=8)),
                ('output_url', models.CharField(blank=True, help_text='MinIO 接入后存储回显对象 URL', max_length=255)),
                ('output', common.crypto.EncryptedTextField(blank=True, default='', help_text='回显全文（加密内联存储，偏差见文件头注释）')),
                ('error', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='automate.scriptrun')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['run', 'device_id'], name='detail_run_dev_idx')],
            },
        ),
    ]
