# Generated by Django 6.1 on 2026-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwarePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=32)),
                ('hw_model', models.CharField(blank=True, help_text='适用硬件型号（支持通配 S51*）', max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '固件版本',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareUpgradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('package_id', models.BigIntegerField(blank=True, null=True)),
                ('package_name_snapshot', models.CharField(blank=True, max_length=128)),
                ('package_version_snapshot', models.CharField(blank=True, max_length=64)),
                ('current_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('ready', '预检通过待刷写窗口'), ('running', '执行中'), ('success', '成功(演练)'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='计划执行窗口(可选)', null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result_log', models.TextField(blank=True, help_text='预检/演练回显（真实回显加密接入后改密文）')),
                ('error', models.TextField(blank=True)),
                ('executed_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '固件升级计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
