# Generated by Django 6.1 on 2026-08-20 13:13

import common.crypto
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rule_type', models.CharField(choices=[('must_present', 'Must Present'), ('must_absent', 'Must Absent')], default='must_present', max_length=16)),
                ('pattern', models.TextField(help_text='regex, applied per line')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(default='warning', max_length=8)),
                ('remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('backup_type', models.CharField(choices=[('running', 'Running'), ('startup', 'Startup'), ('full', 'Full')], default='running', max_length=16)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('event', 'Event'), ('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=16)),
                ('content', common.crypto.EncryptedTextField()),
                ('size', models.IntegerField(default=0)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'config backup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_backup_id', models.BigIntegerField(blank=True, null=True)),
                ('new_backup_id', models.BigIntegerField()),
                ('changed_lines', models.IntegerField(default=0)),
                ('diff_text', models.TextField(blank=True)),
                ('related_alert_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BaselineCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('compliant', models.BooleanField(default=True)),
                ('matched_content', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ncm.baselinerule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
