# Generated by Django 6.1 on 2026-08-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_at', models.DateTimeField(db_index=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(default='ssh', max_length=16)),
                ('result', models.CharField(default='success', max_length=8)),
                ('source', models.CharField(default='syslog', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('usage_type', models.CharField(choices=[('reserve', 'Reserve'), ('occupy', 'Occupy')], default='reserve', max_length=8)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('released', 'Released'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='reserved', max_length=16)),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('ticket_no', models.CharField(blank=True, max_length=64)),
                ('released_by_id', models.BigIntegerField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
