# Generated by Django 6.1 on 2026-08-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidr', models.CharField(max_length=18, unique=True)),
                ('vlan_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=128)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('site_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vid', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('site_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=128)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vid'],
                'constraints': [models.UniqueConstraint(fields=('vid', 'site_id'), name='uq_vlan_vid_site')],
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('used', 'Used'), ('reserved', 'Reserved'), ('conflict', 'Conflict')], default='used', max_length=16)),
                ('device_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('interface_id', models.BigIntegerField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=32)),
                ('assignee', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('arp_discover', 'Arp'), ('dhcp', 'Dhcp')], default='manual', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='ipam.subnet')),
            ],
            options={
                'ordering': ['address'],
                'constraints': [models.UniqueConstraint(fields=('subnet', 'address'), name='uq_ip_subnet_addr')],
            },
        ),
    ]
