# Generated by Django 6.1 on 2026-08-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(max_length=8)),
                ('timeout_min', models.IntegerField(default=15)),
                ('escalate_role_id', models.BigIntegerField(blank=True, null=True)),
                ('channel_ids', models.JSONField(blank=True, default=list)),
                ('fired_count', models.IntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedup_key', models.CharField(db_index=True, max_length=128)),
                ('rule_id', models.BigIntegerField(blank=True, null=True)),
                ('inspect_item_id', models.BigIntegerField(blank=True, null=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('interface_id', models.BigIntegerField(blank=True, null=True)),
                ('severity', models.CharField(default='warning', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('acknowledged', 'Acknowledged'), ('processing', 'Processing'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='firing', max_length=16)),
                ('fired_count', models.IntegerField(default=1)),
                ('first_fired_at', models.DateTimeField(auto_now_add=True)),
                ('last_fired_at', models.DateTimeField(auto_now=True)),
                ('acked_by_id', models.BigIntegerField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_id', models.BigIntegerField(blank=True, null=True)),
                ('process_note', models.TextField(blank=True)),
                ('suppressed_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rule_type', models.CharField(choices=[('metric_threshold', 'Metric'), ('state', 'State'), ('log_keyword', 'Log'), ('trap', 'Trap')], default='metric_threshold', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('metric', models.CharField(blank=True, max_length=128)),
                ('operator', models.CharField(default='>', max_length=8)),
                ('threshold', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('for_duration_s', models.IntegerField(default=300)),
                ('severity', models.CharField(default='warning', max_length=8)),
                ('log_pattern', models.CharField(blank=True, max_length=512)),
                ('notify_channels', models.JSONField(blank=True, default=list)),
                ('notify_users', models.JSONField(blank=True, default=list)),
                ('dedup_window_s', models.IntegerField(default=600)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertSilence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('silence_type', models.CharField(default='maintenance', max_length=16)),
                ('device_usage_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='queued', max_length=8)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel_msg_id', models.CharField(blank=True, max_length=64)),
                ('interaction_status', models.CharField(blank=True, max_length=16)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alert.alertevent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
