# Generated by Django 6.1 on 2026-09-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', '人工报障'), ('alert', '告警联动'), ('inspect', '巡检异常')], db_index=True, default='manual', max_length=8)),
                ('reporter_id', models.BigIntegerField(db_index=True)),
                ('handler_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('mid', '中'), ('low', '低')], db_index=True, default='mid', max_length=8)),
                ('status', models.CharField(choices=[('new', '待分派'), ('assigned', '处理中(已分派)'), ('processing', '处理中'), ('feedback', '待反馈确认'), ('closed', '已关闭')], db_index=True, default='new', max_length=16)),
                ('related_alert_event_id', models.BigIntegerField(blank=True, null=True)),
                ('device_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '事件单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('comment', '评论'), ('assign', '分派'), ('status_change', '状态变更'), ('sla_warning', 'SLA 超时提醒')], default='comment', max_length=16)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='change.incidentticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
