# Generated by Django 6.1 on 2026-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('config', '配置变更'), ('device', '设备变更'), ('sw_upgrade', '软件升级'), ('network', '网络变更')], db_index=True, default='config', max_length=16)),
                ('risk_level', models.CharField(choices=[('high', '高危'), ('mid', '中危'), ('low', '低危')], db_index=True, default='mid', max_length=8)),
                ('plan_start', models.DateTimeField(blank=True, null=True)),
                ('plan_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approving', '待审批'), ('approved', '已批准'), ('implementing', '实施中'), ('verifying', '验证中'), ('closed', '已关闭'), ('rejected', '已驳回'), ('rolledback', '已回滚')], db_index=True, default='draft', max_length=16)),
                ('applicant_id', models.BigIntegerField(db_index=True)),
                ('implementer_id', models.BigIntegerField(blank=True, null=True)),
                ('verifier_id', models.BigIntegerField(blank=True, null=True)),
                ('approver_id', models.BigIntegerField(blank=True, null=True)),
                ('approval_id', models.BigIntegerField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='变更内容与影响面 {summary, impact, steps, affected_device_ids}')),
                ('related_script_run_id', models.BigIntegerField(blank=True, null=True)),
                ('related_config_event_id', models.BigIntegerField(blank=True, null=True)),
                ('rollback_plan', models.TextField(blank=True)),
                ('result_desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '变更单',
                'ordering': ['-created_at'],
            },
        ),
    ]
